name: rise_together
description: "A joint action experimental paradigm for collaboration and competition"
publish_to: 'none'
version: 0.4.0

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  #liblsl: ^0.8.0
  liblsl:
    path: ../liblsl.dart/packages/liblsl
  # temporary local dependency for liblsl_coordinator
  # to be removed when liblsl_coordinator is published
  liblsl_coordinator: 
    path: ../liblsl.dart/packages/liblsl_coordinator
  cupertino_icons: ^1.0.8
  flame_forge2d: ^0.19.0+2
  flame: ^1.29.0
  logging: ^1.3.0
  easy_localization: ^3.0.8
  flutter_fullscreen: ^1.1.0
  wakelock_plus: ^1.3.2
  flutter_multicast_lock: ^1.1.1
  flutter_refresh_rate_control: ^0.0.3+1
  easy_shared_preferences: ^1.1.0
  provider: ^6.1.5
  meta: ^1.16.0
  flutter_colorpicker: ^1.1.0
  synchronized: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_console: ^0.1.2
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.1
flutter:
  uses-material-design: false
  assets:
    - assets/images/
    - assets/translations/
